### ISSUE TITLE
Build fails after e1fe1d264bc5363e008d23fea9d8c5d2ac0d8198

### ISSUE THREAD

**Issue by mat813** [auth0/express-jwt#296]
### Description

After upgrading to v7.7.3, my application fails to build with:

```
apps/index-generator.ts:156:22 - error TS2349: This expression is not callable.
  Type '{ default: { (options: Options): RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>; (options: ((req: Request<...>) => boolean) | undefined): RequestHandler<...>; (middleware: RequestHandler<...>, options: Options): RequestHandler<...>; }; }' has no call signatures.

156         ? jwtHandler.unless(unlessOptions)
                         ~~~~~~

  node_modules/express-jwt/dist/index.d.ts:3:1
    3 import * as expressUnless from 'express-unless';
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.

```

### Reproduction

```typescript
    const jwtHandler = expressjwt(jwtProperties);

    app.use(jwtHandler.unless(unlessOptions));
```

The problem is from using `import * as expressUnless from 'express-unless';` instead of `import expressUnless from 'express-unless';`. When you use `* as` the default export is available in `.default` so you probably need to change https://github.com/auth0/express-jwt/blob/master/src/index.ts#L180 to `middleware.unless = expressUnless.default;`.

### Environment

- **Version of this library used:** v7.7.3
- **Version of the platform or framework used, if applicable:** nodejs v16.13.2
- **Other modules/plugins/libraries that might be involved:** typescript 4.7.2

**Comment by jfromaniello** [comment]
Related to #291 , ping @ItzRabbs ... what should we do? 😱

**Comment by jfromaniello** [comment]
Can you show me your tsconfig, please?

**Comment by ItzRabbs** [comment]
That's so odd, it works perfectly fine for me. In fact, doing `import expressUnless from 'express-unless';` generated the error for me.

**Comment by jfromaniello** [comment]
what if you use `esModuleInterop: true` in your project?

BTW, is it common to rebuild stuff inside node_modules? I am kind of lost here

**Comment by ItzRabbs** [comment]
I don't have a choice on `esModuleInterop` unfortunately.

Would you object if I try and PR into `express-unless` and convert that to typescript? I think that would avoid the issues here.

**Comment by jfromaniello** [comment]
@ItzRabbs not at all! I really appreciate your work and effort

**Comment by ItzRabbs** [comment]
Alright, I'll get to that today

**Comment by ItzRabbs** [comment]
@jfromaniello Take a look at https://github.com/jfromaniello/express-unless/pull/33 when you can

**Comment by jfromaniello** [comment]
Yes! that was it .. I just published a new version of express-unless including the missing files and it worked now

@mat813 can you try with `express-jwt@7.7.4`? Thank you

**Comment by ItzRabbs** [comment]
I do see one issue with a missing RegExp type for path.url. Opened a PR: https://github.com/jfromaniello/express-unless/pull/34

**Comment by jfromaniello** [comment]
ok! Updated in `express-jwt@7.7.5`

**Comment by jfromaniello** [comment]
hi @mat813 , I just pushed `express-unless@2.1.0` which export the type `Params`

**Comment by mat813** [comment]
Thank you all, with `express-unless@2.1.0` I was able to update to `express-jwt@7.7.5`.
